apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: behemoth-apps-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels: {}
  namespaceSelector:
    matchNames:
      - behemoth
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
