apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: behemoth-api-gateway
  namespace: behemoth
spec:
  entryPoints:
    - web
  routes:
  # ROUTE 1: auth
  - match: Host(`behemoth-api-gateway.192.168.100.78.nip.io`) && PathPrefix(`/api/auth`)
    kind: Rule
    services:
    - name: behemoth-auth-service
      port: 3010

  # ROUTE 2: movies
  - match: Host(`behemoth-api-gateway.192.168.100.78.nip.io`) && PathPrefix(`/api/movies`)
    kind: Rule
    services:
    - name: behemoth-movie-service
      port: 3020

  # ROUTE 3: review
  - match: Host(`behemoth-api-gateway.192.168.100.78.nip.io`) && PathPrefix(`/api/review`)
    kind: Rule
    services:
    - name: behemoth-review-service
      port: 3030
