apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: behemoth-nodejs-catalog
    app.kubernetes.io/part-of: behemoth
  name: behemoth-nodejs-catalog
  namespace: behemoth
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3020
  selector:
    app.kubernetes.io/name: behemoth-nodejs-catalog
    app.kubernetes.io/part-of: behemoth
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: behemoth-nodejs-catalog
    app.kubernetes.io/part-of: behemoth
  name: behemoth-nodejs-catalog
  namespace: behemoth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: behemoth-nodejs-catalog
      app.kubernetes.io/part-of: behemoth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: behemoth-nodejs-catalog
        app.kubernetes.io/part-of: behemoth
    spec:
      containers:
      - env:
        - name: PORT
          value: "3020"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: behemoth-db-password
        - name: OMDB_API_KEY
          valueFrom:
            secretKeyRef:
              key: OMDB_API_KEY
              name: behemoth-omdb-apikey
        envFrom:
        - configMapRef:
            name: behemoth-db-config
        image: registry.local:5000/behemoth-catalog-service:latest
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 3020
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
        name: behemoth-nodejs-catalog
        ports:
        - containerPort: 3020
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/readyness
            port: 3020
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /health/startup
            port: 3020
          periodSeconds: 10
        volumeMounts:
        - mountPath: /app/keys/public.pem
          name: keys-volume
          readOnly: true
          subPath: public.pem
      volumes:
      - name: keys-volume
        secret:
          secretName: behemoth-keys
