apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-service-monitor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://192.168.100.78:3000/alfathmuqoddas/behemoth-app-manifest.git
    targetRevision: main
    path: monitoring/new/argocd-servicemonitor

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
